name = "cloud-nav"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

routes = [
  { pattern = "nav.jiuge.ai", custom_domain = true }
]

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[[d1_databases]]
binding = "DB"
database_name = "jiugenav"
database_id = "54340279-33f5-4f57-98db-c70316233a49"
migrations_dir = "drizzle"

[ai]
binding = "AI"